In [1]:
import pandas as pd
pd.options.display.max_columns = 200
pd.options.display.float_format = '{:.3f}'.format
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.neighbors import KNeighborsClassifier, NearestNeighbors
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
link_bas = r"/Users/margaryta/Desktop/WILD/Project 2/movie_final_ML1.csv"
movie_final= pd.read_csv(link_bas, low_memory = False)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/margaryta/Desktop/WILD/Project 2/movie_final_ML1.csv'

In [3]:
movie_final.head()

NameError: name 'movie_final' is not defined

In [7]:
movie_final[movie_final["originalTitle"] == 'Inception']

Unnamed: 0     tconst originalTitle  isAdult  runtimeMinutes  \
42905       42905  tt1375666     Inception        0             148   

                      genres_x    title_x  averageRating  numVotes  \
42905  Action Adventure Sci-Fi  Inception          8.800   2544404   

                          backdrop_path     id    imdb_id original_language  \
42905  /8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg  27205  tt1375666                EN   

                                                overview  popularity  \
42905  Cobb, a skilled thief who commits corporate es...      77.103   

                            poster_path  release_date  Drama  Adventure  \
42905  /edv5CZvWj09upOsy2Y6IwDhK8bt.jpg          2010      0          1   

       Fantasy  Biography  Romance  History  Comedy  Crime  Mystery  Horror  \
42905        0          0        0        0       0      0        0       0   

       Western  Action  Family  War  Sci-Fi  Thriller  Sport  Documentary  \
42905        0       1       0    0       1         0      0            0   

       Music  Animation  Film-Noir  News  director1    writer1     actor1  \
42905      0          0          0     0  nm0634240  nm0634240  nm0000138   

          actor2     actor3  
42905  nm0330687  nm0680983

In [8]:
movie_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59682 entries, 0 to 59681
Data columns (total 44 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         59682 non-null  int64  
 1   tconst             59682 non-null  object 
 2   originalTitle      59682 non-null  object 
 3   isAdult            59682 non-null  int64  
 4   runtimeMinutes     59682 non-null  int64  
 5   genres_x           59682 non-null  object 
 6   title_x            59682 non-null  object 
 7   averageRating      59682 non-null  float64
 8   numVotes           59682 non-null  int64  
 9   backdrop_path      47754 non-null  object 
 10  id                 59682 non-null  int64  
 11  imdb_id            59682 non-null  object 
 12  original_language  59682 non-null  object 
 13  overview           57908 non-null  object 
 14  popularity         59682 non-null  float64
 15  poster_path        58112 non-null  object 
 16  release_date       596

In [62]:
movie_final.columns

Index(['Unnamed: 0', 'tconst', 'originalTitle', 'isAdult', 'runtimeMinutes',
       'genres_x', 'title_x', 'averageRating', 'numVotes', 'backdrop_path',
       'id', 'imdb_id', 'original_language', 'overview', 'popularity',
       'poster_path', 'release_date', 'Drama', 'Adventure', 'Fantasy',
       'Biography', 'Romance', 'History', 'Comedy', 'Crime', 'Mystery',
       'Horror', 'Western', 'Action', 'Family', 'War', 'Sci-Fi', 'Thriller',
       'Sport', 'Documentary', 'Music', 'Animation', 'Film-Noir', 'News',
       'director1', 'writer1', 'actor1', 'actor2', 'actor3'],
      dtype='object')

In [67]:
X = movie_final.drop(columns=['Unnamed: 0', 'tconst', 'originalTitle', 'title_x', 'backdrop_path',
       'id', 'imdb_id', 'overview', 'poster_path'])

In [94]:
numeric_cols = ["runtimeMinutes", "averageRating", "numVotes","popularity", "release_date"]

category_cols = ["isAdult", "original_language", "director1", "writer1", "actor1", "actor2", "actor3"]

pass_cols = ['Drama', 'Adventure', 'Fantasy',
       'Biography', 'Romance', 'History', 'Comedy', 'Crime', 'Mystery',
       'Horror', 'Western', 'Action', 'Family', 'War', 'Sci-Fi', 'Thriller',
       'Sport', 'Documentary', 'Music', 'Animation', 'Film-Noir', 'News']

num_preprocessor = StandardScaler()
cat_preprocessor = OneHotEncoder()

model_nearest = (
                    make_pipeline(
    ColumnTransformer(
                                    [
                                        ('OneHotEncoder', cat_preprocessor, category_cols),
                                        ('StandardScaler', num_preprocessor, numeric_cols),
                                        ( 'already_factorized','passthrough', pass_cols)
                                    ]
                         ),
    NearestNeighbors(n_neighbors = 3)  ))
model_nearest

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('OneHotEncoder',
                                                  OneHotEncoder(),
                                                  ['isAdult',
                                                   'original_language',
                                                   'director1', 'writer1',
                                                   'actor1', 'actor2',
                                                   'actor3']),
                                                 ('StandardScaler',
                                                  StandardScaler(),
                                                  ['runtimeMinutes',
                                                   'averageRating', 'numVotes',
                                                   'popularity',
                                                   'release_date']),
                                                 ('factorized', 'passthrough',
                                                  ['Drama', 'Adventure',
                                                   'Fantasy', 'Biography',
                                                   'Romance', 'History',
                                                   'Comedy', 'Crime', 'Mystery',
                                                   'Horror', 'Western',
                                                   'Action', 'Family', 'War',
                                                   'Sci-Fi', 'Thriller',
                                                   'Sport', 'Documentary',
                                                   'Music', 'Animation',
                                                   'Film-Noir', 'News'])])),
                ('nearestneighbors', NearestNeighbors(n_neighbors=3))])

In [95]:
model_nearest.fit(X)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('OneHotEncoder',
                                                  OneHotEncoder(),
                                                  ['isAdult',
                                                   'original_language',
                                                   'director1', 'writer1',
                                                   'actor1', 'actor2',
                                                   'actor3']),
                                                 ('StandardScaler',
                                                  StandardScaler(),
                                                  ['runtimeMinutes',
                                                   'averageRating', 'numVotes',
                                                   'popularity',
                                                   'release_date']),
                                                 ('factorized', 'passthrough',
                                                  ['Drama', 'Adventure',
                                                   'Fantasy', 'Biography',
                                                   'Romance', 'History',
                                                   'Comedy', 'Crime', 'Mystery',
                                                   'Horror', 'Western',
                                                   'Action', 'Family', 'War',
                                                   'Sci-Fi', 'Thriller',
                                                   'Sport', 'Documentary',
                                                   'Music', 'Animation',
                                                   'Film-Noir', 'News'])])),
                ('nearestneighbors', NearestNeighbors(n_neighbors=3))])

In [96]:
X_transformed = model_nearest.named_steps['columntransformer'].fit_transform(X) 

In [111]:
movie_final[movie_final['originalTitle'] == "Sully"].index

Int64Index([51125], dtype='int64')

In [97]:
#Aff dataframe 
model_nearest.named_steps['nearestneighbors'].kneighbors(X_transformed, n_neighbors = 3) 

(array([[0.        , 2.07787695, 2.84868022],
        [0.        , 2.49935588, 2.68534355],
        [0.        , 3.38346723, 3.47299454],
        ...,
        [0.        , 3.71659355, 3.72584191],
        [0.        , 1.4594749 , 1.5955671 ],
        [0.        , 2.64596599, 2.64672906]]),
 array([[    0, 59608,   101],
        [    1,   301,   194],
        [    2,    14, 29038],
        ...,
        [59679, 44493, 49556],
        [59680, 43404, 54119],
        [59681, 56416, 51801]]))

In [116]:
model_nearest.named_steps['nearestneighbors'].kneighbors(X_transformed[51125], n_neighbors = 3) 

(array([[0.        , 2.72121814, 2.88606588]]), array([[51125, 37392, 51857]]))

In [90]:
 movie_final[movie_final['originalTitle'] == "Sully"]

Unnamed: 0     tconst originalTitle  isAdult  runtimeMinutes  \
51125       51125  tt3263904         Sully        0              96   

              genres_x title_x  averageRating  numVotes  \
51125  Biography Drama   Sully          7.400    297414   

                          backdrop_path      id    imdb_id original_language  \
51125  /phWZP5FESItyhQcqk6sWz35nUtP.jpg  363676  tt3263904                EN   

                                                overview  popularity  \
51125  On 15 January 2009, the world witnessed the 'M...      21.665   

                            poster_path  release_date  Drama  Adventure  \
51125  /r09ivJ1GGh5WArqRViRYDQLrTVG.jpg          2016      1          0   

       Fantasy  Biography  Romance  History  Comedy  Crime  Mystery  Horror  \
51125        0          1        0        0       0      0        0       0   

       Western  Action  Family  War  Sci-Fi  Thriller  Sport  Documentary  \
51125        0       0       0    0       0         0      0            0   

       Music  Animation  Film-Noir  News  director1    writer1     actor1  \
51125      0          0          0     0  nm0000142  nm0464548  nm0000158   

          actor2         actor3  
51125  nm0001173  non renseigné

In [117]:
movie_final.iloc[37392]

Unnamed: 0                                                       37392
tconst                                                       tt0824747
originalTitle                                               Changeling
isAdult                                                              0
runtimeMinutes                                                     141
genres_x                                         Biography Crime Drama
title_x                                                      L'échange
averageRating                                                    7.800
numVotes                                                        265042
backdrop_path                         /hmw8oa2aJvhKbfibs8dp3vsNCDI.jpg
id                                                                3580
imdb_id                                                      tt0824747
original_language                                                   EN
overview             Christine Collins is overjoyed when her kidnap...
popula

In [108]:
movie_final.iloc[56416]

Unnamed: 0                                      56416
tconst                                      tt7091466
originalTitle          Derniers remords avant l'oubli
isAdult                                             0
runtimeMinutes                                     84
genres_x                                        Drama
title_x                Derniers remords avant l'oubli
averageRating                                   0.000
numVotes                                            0
backdrop_path                                     NaN
id                                             649912
imdb_id                                     tt7091466
original_language                                  FR
overview                                          NaN
popularity                                      0.600
poster_path          /mSQWPNbVawBzAD0PG4foPlawlOD.jpg
release_date                                     2018
Drama                                               1
Adventure                   